user:
  name: 50 
  email: 225
  validate_email_rex: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  password: 6
  gravatar: 80
  gravatar_small: 50
  avatar: 30

links:
  rails_tutorial: "http://railstutorial.org"
  michael: "https://www.railstutorial.org/"
  news: "http://news.railstutorial.org/"
  contact: "https://www.railstutorial.org/contact"
  ruby_on_rails: "http://rubyonrails.org/"
  guide: "http://screencasts.railstutorial.org"
  book: "https://www.railstutorial.org/book"
  help: "https://www.railstutorial.org/help"

micropost:
  content: 140
  size: 50
  photo_size: 5
